
server:
  port: 8761 # Eureka ?? ??

spring:
  application:
    name: eureka-server # ??? ?? ??? ?? ??

eureka:
  client:
    register-with-eureka: false # ??? ?? ?? ? true
    fetch-registry: false #?? ??? ??? ?? ??.
  server:
    enable-self-preservation: false
